[package]
name = "get"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.13.3"
home = "0.5.4"
serde = "1.0.152"
serde_yaml = "0.9.16"
structopt = "0.3.26"

